name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version-file: ".tool-versions"
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: Test
        run: npm test

      - name: Integration tests
        run: npm run test:integration
        env:
          PI_OFFLINE: "1"
